#!/usr/bin/env bash
# Rebuild wasm/resource-pack from the full resource/ tree.
# Desktop builds continue to use resource/; only the WASM packaging is scoped.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/resource"
DEST="$ROOT/wasm/resource-pack"

rm -rf "$DEST"
mkdir -p "$DEST/userdata_original/savestate" "$DEST/userdata_original/layouts"

copy_if_exists() {
  local rel="$1"
  if [ -f "$SRC/$rel" ]; then
    mkdir -p "$DEST/$(dirname "$rel")"
    cp "$SRC/$rel" "$DEST/$rel"
  else
    echo "warning: missing $SRC/$rel" >&2
  fi
}

copy_if_exists "userdata_original/scales.json"
copy_if_exists "userdata_original/savestate/wasm-starter.bsk"
copy_if_exists "userdata_original/layouts/blank.json"
copy_if_exists "userdata_original/userdata_version.txt"

cat > "$DEST/README.md" << 'EOF'
# WASM resource pack (minimal preload)

Generated by `scripts/prepare_wasm_resource_pack.sh`. See that script and
`docs/wasm/resources.md` for the packaging policy.
EOF

echo "WASM resource pack:"
du -sh "$DEST"
find "$DEST" -type f | sort
